apiVersion: apps/v1
kind: Deployment
metadata:
  name: crashy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crashy-app
  template:
    metadata:
      labels:
        app: crashy-app
    spec:
      containers:
      - name: crashy-container
        image: busybox
        command: ["/bin/sh", "-c", "exit 1"] # This will cause CrashLoopBackOff
